import { spawnSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"

import { bulletToTsExpr } from "experience-sync/lib/markdown"
import { EXPERIENCES_OUTPUT, REPO_ROOT } from "experience-sync/lib/paths"
import type { Company, ExperiencesDocument } from "experience-sync/lib/schema"
import { arr, emitTsExpr, ident, lit, obj, type TsExpr } from "experience-sync/lib/tsEmit"

/** Derive a stable JS import identifier from a logo filename (e.g. `Intuit.svg` → `IntuitLogo`). */
function logoImportName(logoFile: string): string {
  const base = path.basename(logoFile, path.extname(logoFile))
  return (
    base
      .replace(/[^a-zA-Z0-9]+/g, "_")
      .replace(/^(\d)/, "_$1")
      .replace(/_+/g, "_") + "Logo"
  )
}

function roleToTsExpr(role: Company["roles"][number]): TsExpr {
  const bulletPoints = role.accomplishments
    .filter((a) => a.destinations.includes("portfolio") && a.variants.portfolio?.trim())
    .map((a) => bulletToTsExpr(a.variants.portfolio!.trim()))

  return obj({
    position: lit(role.position),
    start: obj({
      month: lit(role.start.month),
      year: lit(role.start.year),
    }),
    end: role.end
      ? obj({
          month: lit(role.end.month),
          year: lit(role.end.year),
        })
      : undefined,
    bulletPoints: arr(bulletPoints),
  })
}

function companyToTsExpr(company: Company): TsExpr {
  return obj({
    companyName: lit(company.companyName),
    location: lit(company.location),
    roles: arr(company.roles.map(roleToTsExpr)),
    technologies: arr(company.technologies.map((t) => ident(`technologies.${t}`))),
    logo: ident(logoImportName(company.logoFile)),
    color: ident(`COLORS.${company.colorKey}`),
  })
}

/**
 * Generate the TypeScript source for `src/data/experiences.ts`.
 * Portfolio-only: filters accomplishments to the `portfolio` destination and expands markdown links.
 */
export function generateExperiencesTs(doc: ExperiencesDocument): string {
  const logoImports = doc.companies
    .map((c) => {
      const name = logoImportName(c.logoFile)
      return `import ${name} from "assets/Company_Logos/${c.logoFile}"`
    })
    .join("\n")

  const experiencesExpr = arr(doc.companies.map(companyToTsExpr))

  return `/**
 * @generated by \`yarn exp:generate\` — do not edit by hand.
 * Source of truth: experience-sync/content/experiences.yaml
 */
import { COLORS } from "data/colors"
import * as technologies from "data/technologies"
import { Experience } from "types/experience.types"
import { createExternalLink } from "utils/contentUtils"
${logoImports}

export const experiences: Experience[] = ${emitTsExpr(experiencesExpr)}
`
}

/**
 * Write generated `experiences.ts` and run Prettier on it.
 * @returns Absolute path of the written file
 */
export function writeExperiencesTs(doc: ExperiencesDocument): string {
  const source = generateExperiencesTs(doc)
  fs.mkdirSync(path.dirname(EXPERIENCES_OUTPUT), { recursive: true })
  fs.writeFileSync(EXPERIENCES_OUTPUT, source, "utf8")

  const prettierBin = path.join(REPO_ROOT, "node_modules/.bin/prettier")
  const formatted = spawnSync(prettierBin, ["--write", EXPERIENCES_OUTPUT], {
    cwd: REPO_ROOT,
    encoding: "utf8",
  })
  if (formatted.status !== 0) {
    console.warn("Warning: prettier failed on generated experiences.ts")
    if (formatted.stderr) {
      console.warn(formatted.stderr)
    }
  }

  return EXPERIENCES_OUTPUT
}
