import { spawnSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"

import { emitBulletArrayLiteral } from "experience-sync/lib/markdown"
import { EXPERIENCES_OUTPUT, REPO_ROOT } from "experience-sync/lib/paths"
import type { Company, ExperiencesDocument } from "experience-sync/lib/schema"

/** Derive a stable JS import identifier from a logo filename (e.g. `Intuit.svg` → `IntuitLogo`). */
function logoImportName(logoFile: string): string {
  const base = path.basename(logoFile, path.extname(logoFile))
  return (
    base
      .replace(/[^a-zA-Z0-9]+/g, "_")
      .replace(/^(\d)/, "_$1")
      .replace(/_+/g, "_") + "Logo"
  )
}

/** Emit one role object literal for `experiences.ts` (portfolio bullets only). */
function emitRole(role: Company["roles"][number], indent: string): string {
  const bullets = role.accomplishments
    .filter((a) => a.destinations.includes("portfolio") && a.variants.portfolio?.trim())
    .map((a) => emitBulletArrayLiteral(a.variants.portfolio!.trim(), indent + "    "))

  const endLine = role.end ? `\n${indent}  end: { month: ${JSON.stringify(role.end.month)}, year: ${role.end.year} },` : ""

  const bulletBlock =
    bullets.length === 0 ? `${indent}  bulletPoints: [],` : `${indent}  bulletPoints: [\n${bullets.join(",\n")},\n${indent}  ],`

  return `${indent}{
${indent}  position: ${JSON.stringify(role.position)},
${indent}  start: { month: ${JSON.stringify(role.start.month)}, year: ${role.start.year} },${endLine}
${bulletBlock}
${indent}}`
}

/** Emit one company object literal for `experiences.ts` (logo + COLORS + technologies). */
function emitCompany(company: Company, indent: string): string {
  const logoName = logoImportName(company.logoFile)
  const roles = company.roles.map((r) => emitRole(r, indent + "  ")).join(",\n")
  const techs = company.technologies.map((t) => `${indent}  technologies.${t},`).join("\n")

  return `${indent}{
${indent}  companyName: ${JSON.stringify(company.companyName)},
${indent}  location: ${JSON.stringify(company.location)},
${indent}  roles: [
${roles},
${indent}  ],
${indent}  technologies: [
${techs}
${indent}  ],
${indent}  logo: ${logoName},
${indent}  color: COLORS.${company.colorKey},
${indent}}`
}

/**
 * Generate the TypeScript source for `src/data/experiences.ts`.
 * Portfolio-only: filters accomplishments to the `portfolio` destination and expands markdown links.
 */
export function generateExperiencesTs(doc: ExperiencesDocument): string {
  const logoImports = doc.companies
    .map((c) => {
      const name = logoImportName(c.logoFile)
      return `import ${name} from "assets/Company_Logos/${c.logoFile}"`
    })
    .join("\n")

  const companies = doc.companies.map((c) => emitCompany(c, "  ")).join(",\n")

  return `/**
 * @generated by \`yarn exp:generate\` — do not edit by hand.
 * Source of truth: experience-sync/content/experiences.yaml
 */
import { COLORS } from "data/colors"
import * as technologies from "data/technologies"
import { Experience } from "types/experience.types"
import { createExternalLink } from "utils/contentUtils"
${logoImports}

export const experiences: Experience[] = [
${companies},
]
`
}

/**
 * Write generated `experiences.ts` and run Prettier on it.
 * @returns Absolute path of the written file
 */
export function writeExperiencesTs(doc: ExperiencesDocument): string {
  const source = generateExperiencesTs(doc)
  fs.mkdirSync(path.dirname(EXPERIENCES_OUTPUT), { recursive: true })
  fs.writeFileSync(EXPERIENCES_OUTPUT, source, "utf8")

  const prettierBin = path.join(REPO_ROOT, "node_modules/.bin/prettier")
  const formatted = spawnSync(prettierBin, ["--write", EXPERIENCES_OUTPUT], {
    cwd: REPO_ROOT,
    encoding: "utf8",
  })
  if (formatted.status !== 0) {
    console.warn("Warning: prettier failed on generated experiences.ts")
    if (formatted.stderr) {
      console.warn(formatted.stderr)
    }
  }

  return EXPERIENCES_OUTPUT
}
