/**
 * @generated by `yarn exp:generate` — do not edit by hand.
 * Source of truth: experience-sync/content/experiences.yaml
 */
import ArculesLogo from "assets/Company_Logos/Arcules.svg"
import ID_TechLogo from "assets/Company_Logos/ID_Tech.svg"
import IntuitLogo from "assets/Company_Logos/Intuit.svg"
import RaytheonLogo from "assets/Company_Logos/Raytheon.svg"
import ReazonLogo from "assets/Company_Logos/Reazon.svg"
import { COLORS } from "data/colors"
import * as technologies from "data/technologies"
import { Experience } from "types/experience.types"
import { createExternalLink } from "utils/contentUtils"

export const experiences: Experience[] = [
  {
    companyName: "Intuit",
    location: "San Diego, CA",
    roles: [
      {
        position: "Senior Software Engineer",
        start: {
          month: "Aug",
          year: 2026,
        },
        bulletPoints: [
          [
            "Full stack engineer on the appointments team for Intuit's ",
            createExternalLink(
              "Virtual Expert Platform",
              "https://investors.intuit.com/news-events/press-releases/detail/100/intuits-virtual-expert-platform-connects-people-to-tax-and-bookkeeping-experts-powered-by-ai",
            ),
            ". across TurboTax, QuickBooks, Credit Karma, and Mailchimp.",
          ],
          [
            "Decoupled one on one appointments from Amazon Connect at 600 TPS with zero incidents, unlocking a new offering for independent tax experts, eliminating Connect licenses, and cutting appointment failures by 8%.",
          ],
          [
            "Led development of a feature (using React, Redux and Kafka), enabling experts to receive next appointment alerts during active calls, shipping defect free during last two weeks of tax season for 30,000 experts and reducing missed appointments by 23%.",
          ],
        ],
      },
      {
        position: "Software Engineer 2 - Full Stack",
        start: {
          month: "Oct",
          year: 2023,
        },
        end: {
          month: "Jul",
          year: 2026,
        },
        bulletPoints: [
          [
            "Launched Attribute Based Routing (ABR), retrofitting legacy queue-based routing systems to match customers to tax experts at a more granular level, driving an 11% reduction in TurboTax Live customer service time and a 7% increase in same-day tax filings, for $5.3M in savings.",
          ],
          [
            "Owned end to end delivery of ABR Evolution (autonomous skill prioritization, attribute model redesign) using Java and Spring Boot, from requirements, design, decisions, and technical leadership, improving global match rate by 14%, average handle time (AHT) by 6%, and $3.7M in AHT savings.",
          ],
          [
            "Developed  service for creating ABR rules with an AI model trained on historical expert and customer interactions, replacing manual ABR rule creation by operators, unlocking $2.1M in AHT savings.",
          ],
        ],
      },
    ],
    technologies: [
      technologies.JAVA,
      technologies.SPRING,
      technologies.REACT,
      technologies.REDUX,
      technologies.TYPESCRIPT,
      technologies.GRAPHQL,
      technologies.AWS,
      technologies.KAFKA,
    ],
    logo: IntuitLogo,
    color: COLORS.INTUIT,
  },
  {
    companyName: "Arcules",
    location: "Irvine, CA",
    roles: [
      {
        position: "Software Engineer",
        start: {
          month: "Jan",
          year: 2022,
        },
        end: {
          month: "Oct",
          year: 2023,
        },
        bulletPoints: [
          [
            "Full stack engineer on the ",
            createExternalLink("video surveillance as a service", "https://www.milestonesys.com/products/software/arcules/"),
            " product team.",
          ],
          [
            "Built a Kubernetes CronJob delivering hourly health status reports across 10,000+ devices to meet a top customer's reliability requirement, enabling proactive issue detection at fleet scale.",
          ],
          [
            "Developed a Go service and scheduler on GCP/Postgres that generated detailed device usage reports, giving the team recurring visibility into customer behavior that previously required manual pulls.",
          ],
          [
            "Designed and shipped a set of microservices powering the Back Office portal's quote/order flow, cutting manual steps for the Sales Ops team and shortening the path from quote to order.",
          ],
          [
            "Revamped the app's core flow and stood up localization infrastructure (React, Redux, react-intl), improving usability and unblocking international rollout.",
          ],
        ],
      },
    ],
    technologies: [
      technologies.GO,
      technologies.POSTGRES,
      technologies.REACT,
      technologies.REDUX,
      technologies.GCP,
      technologies.DOCKER,
      technologies.KUBERNETES,
    ],
    logo: ArculesLogo,
    color: COLORS.ARCULES,
  },
  {
    companyName: "Raytheon Intelligence & Space",
    location: "Los Angeles, CA",
    roles: [
      {
        position: "Software Engineer 1",
        start: {
          month: "Jan",
          year: 2020,
        },
        end: {
          month: "Dec",
          year: 2021,
        },
        bulletPoints: [
          [
            "Backend engineer on the Ground Software team for the ",
            createExternalLink(
              "Next Gen Space Based Early Missile Warning System",
              "https://www.rtx.com/news/news-center/2024/09/30/rtxs-raytheon-delivers-missile-warning-sensor",
            ),
            ".",
          ],
          [
            "Built a C++11 / Kafka / Protobuf data processing ",
            createExternalLink("framework", "https://www.rtx.com/raytheon/what-we-do/space/forge"),
            " ingesting terabytes of real time satellite data daily, engineered for the reliability and fault tolerance a defense system demands.",
          ],
          [
            "Developed space to ground message simulator in Python and C++ that let the team develop and test end to end without physical space hardware, removing a major bottleneck from the dev cycle.",
          ],
        ],
      },
    ],
    technologies: [technologies.CPP, technologies.C, technologies.PYTHON, technologies.DOCKER, technologies.KAFKA, technologies.PROTOBUF],
    logo: RaytheonLogo,
    color: COLORS.RAYTHEON,
  },
  {
    companyName: "ID Tech",
    location: "Cypress, CA",
    roles: [
      {
        position: "Software Engineer Co-op",
        start: {
          month: "Sept",
          year: 2018,
        },
        end: {
          month: "Dec",
          year: 2018,
        },
        bulletPoints: [
          [
            "Created responsive mobile web app ",
            createExternalLink("ViVOstate Terminal Management System (TMS)", "https://www.vivostate.com/"),
            " with Node, Express, and Angular for viewing credit card reader device information and performing remote firmware updates in the field.",
          ],
          [
            "Built a web based barcode scanner to allow easy lookup of a device's status and specs using a smartphone/laptop camera, resulting in a 44% faster average task time.",
          ],
          [
            "Added GPS location tracking for quickly viewing devices on a map, utilizing the ",
            createExternalLink("Google Maps API", "https://developers.google.com/maps/documentation"),
            ".",
          ],
          ["Designed wireframes, mockups and UX flows with Figma for rapidly prototyping designs to stakeholders."],
        ],
      },
    ],
    technologies: [technologies.NODEJS, technologies.EXPRESS, technologies.ANGULAR, technologies.FIGMA],
    logo: ID_TechLogo,
    color: COLORS.ID_TECH,
  },
  {
    companyName: "Reazon Systems",
    location: "Santa Ana, CA",
    roles: [
      {
        position: "Software Engineer Intern",
        start: {
          month: "Jan",
          year: 2018,
        },
        end: {
          month: "Mar",
          year: 2018,
        },
        bulletPoints: [
          [
            "Implemented RCampus online classroom learning tools and RESTful APIs with Java and MySQL for universities such as University of Virginia and Indiana University to use in courses.",
          ],
          [
            "Created Google Sheets parsing tool using the ",
            createExternalLink("Google Sheets API", "https://developers.google.com/sheets/api"),
            " for personalized site designs.",
          ],
        ],
      },
    ],
    technologies: [technologies.JAVA, technologies.MYSQL, technologies.JAVASCRIPT, technologies.HTML5, technologies.CSS3],
    logo: ReazonLogo,
    color: COLORS.REAZON,
  },
]
